# Tells cargo to use certain unstable feature flags

[unstable]
build-std-features = ["compiler-builtins-mem"]  # Enable implementations of memory-related functions
build-std = ["core", "compiler_builtins"]       # Enable recompilation of these libraries

[build]
target = "x86_64-rust_os.json"                  # Passes target to build for

# Makes it easier to run our kernel in QEMU by setting the `runner` configuration
[target.'cfg(target_os = "none")']
runner = "bootimage runner"
